name: update
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - syncrhonize
jobs:
  update:
    name: Update Snapshots
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CI: "true"
      HEAD_REF: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: Set git identity
        run: |-
          echo $HEAD_REF
          echo ${{ github.event.pull_request.head.ref }}
          git config user.name "test-user"
          git push origin HEAD:$HEAD_REF
      
